/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPassengersRouteImport } from './routes/_authenticated/passengers'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedSearchResultsRouteImport } from './routes/_authenticated/search/results'
import { Route as AuthenticatedTrainsIdRouteImport } from './routes/_authenticated/trains.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassengersRoute = AuthenticatedPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchResultsRoute =
  AuthenticatedSearchResultsRouteImport.update({
    id: '/search/results',
    path: '/search/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainsIdRoute = AuthenticatedTrainsIdRouteImport.update({
  id: '/trains/$id',
  path: '/trains/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/search/results': typeof AuthenticatedSearchResultsRoute
  '/trains/$id': typeof AuthenticatedTrainsIdRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/search/results': typeof AuthenticatedSearchResultsRoute
  '/trains/$id': typeof AuthenticatedTrainsIdRoute
  '/search': typeof AuthenticatedSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRoute
  '/_authenticated/passengers': typeof AuthenticatedPassengersRoute
  '/_authenticated/search/results': typeof AuthenticatedSearchResultsRoute
  '/_authenticated/trains/$id': typeof AuthenticatedTrainsIdRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/passengers'
    | '/search/results'
    | '/trains/$id'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/passengers'
    | '/search/results'
    | '/trains/$id'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/passengers'
    | '/_authenticated/search/results'
    | '/_authenticated/trains/$id'
    | '/_authenticated/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passengers': {
      id: '/_authenticated/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof AuthenticatedPassengersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/results': {
      id: '/_authenticated/search/results'
      path: '/search/results'
      fullPath: '/search/results'
      preLoaderRoute: typeof AuthenticatedSearchResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trains/$id': {
      id: '/_authenticated/trains/$id'
      path: '/trains/$id'
      fullPath: '/trains/$id'
      preLoaderRoute: typeof AuthenticatedTrainsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRoute
  AuthenticatedPassengersRoute: typeof AuthenticatedPassengersRoute
  AuthenticatedSearchResultsRoute: typeof AuthenticatedSearchResultsRoute
  AuthenticatedTrainsIdRoute: typeof AuthenticatedTrainsIdRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRoute,
  AuthenticatedPassengersRoute: AuthenticatedPassengersRoute,
  AuthenticatedSearchResultsRoute: AuthenticatedSearchResultsRoute,
  AuthenticatedTrainsIdRoute: AuthenticatedTrainsIdRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
