/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPassengersRouteImport } from './routes/_authenticated/passengers'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedBookScheduleIdRouteImport } from './routes/_authenticated/book.$scheduleId'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedBookingsPnrRouteImport } from './routes/_authenticated/bookings.$pnr'
import { Route as AuthenticatedPaymentReservationIdRouteImport } from './routes/_authenticated/payment.$reservationId'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedSearchResultsRouteImport } from './routes/_authenticated/search/results'
import { Route as AuthenticatedTrainsIdRouteImport } from './routes/_authenticated/trains.$id'
import { Route as AuthenticatedBookingSuccessPnrRouteImport } from './routes/_authenticated/booking.success.$pnr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassengersRoute = AuthenticatedPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedBookScheduleIdRoute =
  AuthenticatedBookScheduleIdRouteImport.update({
    id: '/book/$scheduleId',
    path: '/book/$scheduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsPnrRoute =
  AuthenticatedBookingsPnrRouteImport.update({
    id: '/bookings/$pnr',
    path: '/bookings/$pnr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentReservationIdRoute =
  AuthenticatedPaymentReservationIdRouteImport.update({
    id: '/payment/$reservationId',
    path: '/payment/$reservationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchResultsRoute =
  AuthenticatedSearchResultsRouteImport.update({
    id: '/search/results',
    path: '/search/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainsIdRoute = AuthenticatedTrainsIdRouteImport.update({
  id: '/trains/$id',
  path: '/trains/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingSuccessPnrRoute =
  AuthenticatedBookingSuccessPnrRouteImport.update({
    id: '/booking/success/$pnr',
    path: '/booking/success/$pnr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/book/$scheduleId': typeof AuthenticatedBookScheduleIdRoute
  '/bookings/$pnr': typeof AuthenticatedBookingsPnrRoute
  '/payment/$reservationId': typeof AuthenticatedPaymentReservationIdRoute
  '/search/results': typeof AuthenticatedSearchResultsRoute
  '/trains/$id': typeof AuthenticatedTrainsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/booking/success/$pnr': typeof AuthenticatedBookingSuccessPnrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/passengers': typeof AuthenticatedPassengersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/book/$scheduleId': typeof AuthenticatedBookScheduleIdRoute
  '/bookings/$pnr': typeof AuthenticatedBookingsPnrRoute
  '/payment/$reservationId': typeof AuthenticatedPaymentReservationIdRoute
  '/search/results': typeof AuthenticatedSearchResultsRoute
  '/trains/$id': typeof AuthenticatedTrainsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/booking/success/$pnr': typeof AuthenticatedBookingSuccessPnrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/passengers': typeof AuthenticatedPassengersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/book/$scheduleId': typeof AuthenticatedBookScheduleIdRoute
  '/_authenticated/bookings/$pnr': typeof AuthenticatedBookingsPnrRoute
  '/_authenticated/payment/$reservationId': typeof AuthenticatedPaymentReservationIdRoute
  '/_authenticated/search/results': typeof AuthenticatedSearchResultsRoute
  '/_authenticated/trains/$id': typeof AuthenticatedTrainsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/booking/success/$pnr': typeof AuthenticatedBookingSuccessPnrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/dashboard'
    | '/passengers'
    | '/profile'
    | '/book/$scheduleId'
    | '/bookings/$pnr'
    | '/payment/$reservationId'
    | '/search/results'
    | '/trains/$id'
    | '/admin/'
    | '/bookings/'
    | '/search/'
    | '/booking/success/$pnr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/dashboard'
    | '/passengers'
    | '/profile'
    | '/book/$scheduleId'
    | '/bookings/$pnr'
    | '/payment/$reservationId'
    | '/search/results'
    | '/trains/$id'
    | '/admin'
    | '/bookings'
    | '/search'
    | '/booking/success/$pnr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/passengers'
    | '/_authenticated/profile'
    | '/_authenticated/book/$scheduleId'
    | '/_authenticated/bookings/$pnr'
    | '/_authenticated/payment/$reservationId'
    | '/_authenticated/search/results'
    | '/_authenticated/trains/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/bookings/'
    | '/_authenticated/search/'
    | '/_authenticated/booking/success/$pnr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passengers': {
      id: '/_authenticated/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof AuthenticatedPassengersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/book/$scheduleId': {
      id: '/_authenticated/book/$scheduleId'
      path: '/book/$scheduleId'
      fullPath: '/book/$scheduleId'
      preLoaderRoute: typeof AuthenticatedBookScheduleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$pnr': {
      id: '/_authenticated/bookings/$pnr'
      path: '/bookings/$pnr'
      fullPath: '/bookings/$pnr'
      preLoaderRoute: typeof AuthenticatedBookingsPnrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/$reservationId': {
      id: '/_authenticated/payment/$reservationId'
      path: '/payment/$reservationId'
      fullPath: '/payment/$reservationId'
      preLoaderRoute: typeof AuthenticatedPaymentReservationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/results': {
      id: '/_authenticated/search/results'
      path: '/search/results'
      fullPath: '/search/results'
      preLoaderRoute: typeof AuthenticatedSearchResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trains/$id': {
      id: '/_authenticated/trains/$id'
      path: '/trains/$id'
      fullPath: '/trains/$id'
      preLoaderRoute: typeof AuthenticatedTrainsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/success/$pnr': {
      id: '/_authenticated/booking/success/$pnr'
      path: '/booking/success/$pnr'
      fullPath: '/booking/success/$pnr'
      preLoaderRoute: typeof AuthenticatedBookingSuccessPnrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPassengersRoute: typeof AuthenticatedPassengersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBookScheduleIdRoute: typeof AuthenticatedBookScheduleIdRoute
  AuthenticatedBookingsPnrRoute: typeof AuthenticatedBookingsPnrRoute
  AuthenticatedPaymentReservationIdRoute: typeof AuthenticatedPaymentReservationIdRoute
  AuthenticatedSearchResultsRoute: typeof AuthenticatedSearchResultsRoute
  AuthenticatedTrainsIdRoute: typeof AuthenticatedTrainsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedBookingSuccessPnrRoute: typeof AuthenticatedBookingSuccessPnrRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPassengersRoute: AuthenticatedPassengersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBookScheduleIdRoute: AuthenticatedBookScheduleIdRoute,
  AuthenticatedBookingsPnrRoute: AuthenticatedBookingsPnrRoute,
  AuthenticatedPaymentReservationIdRoute:
    AuthenticatedPaymentReservationIdRoute,
  AuthenticatedSearchResultsRoute: AuthenticatedSearchResultsRoute,
  AuthenticatedTrainsIdRoute: AuthenticatedTrainsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedBookingSuccessPnrRoute: AuthenticatedBookingSuccessPnrRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
